### ISSUE TITLE
"Apply action to the entire result set" does not work with collections

### ISSUE THREAD

**Issue by marcelsip** [Esri/geoportal-server#176]
On the Manage Resources page, the "Apply action to the entire result set" checkbox does not seem to work with result sets filtered by collection - the action is instead applied to all records in the database. To reproduce, enable collections for Geoportal, on the Manage Resources page select records by setting "Is Part of" condition and then apply any action with  "Apply action to the entire result set" checkbox checked.

**Comment by zguo** [comment]
related to #64

**Comment by rmbradley** [comment]
In addition to this issue we are seeing a somewhat similar problem when we assign a collection to a large record set.  

The "Apply action to entire result set" does not function when performing the "Share With" action. No records are modified with the intended collection when this option is selected.  (Refer to the now closed issue #64. The "Share with" action does work but only on one page of a result set and when the "Apply action to entire result set" is left unchecked.   See below:

![image](https://cloud.githubusercontent.com/assets/5430455/22426801/f4da2466-e6bd-11e6-85e8-9ed83c7fe270.png)

This behavior is not the same as when performing other actions with "Apply action to entire result set" is checked - like setting records to Approved, or setting restrictions.  It seems that it works with pre-1.2.7 Actions.  

As a result of this, in order to apply a collection to a large group of records, the action needs to be performed once on each page in the result set. 

This is NOT the same behavior that deals with the "Apply action to entire result set" when the result set is being "FILTERED" by a collection. _This is an undesirable behavior that occurs when "SETTING" a collection_.   
See below:

![image](https://cloud.githubusercontent.com/assets/5430455/22426989/a6b2b662-e6be-11e6-91f4-c070a3f24ce0.png)

We are going to be upgrading soon to 1.2.7 and have tested this issue in that version. If a patch to correct this issue could be issued for 1.2.7 that would be great!
