### ISSUE TITLE
User Invalid after change in ldap

### ISSUE THREAD

**Issue by StefanJaq** [Esri/geoportal-server#187]
Hello.
After a change in the central active directory for a user (the user moved to a different unit within the company), the user wasn't able to log in to the geoportal any more. 
Furthermore the administrator couldn't edit the users setting in the geoportal usermanagement. Not even he could remove the user.
How can this issue be resolved?

![sign_in_github](https://cloud.githubusercontent.com/assets/5549165/10852184/b24be856-7f2f-11e5-9900-b069669d1b4a.png)
![user_admin_github](https://cloud.githubusercontent.com/assets/5549165/10852187/b5e71788-7f2f-11e5-82d6-c2d2342639be.png)

**Comment by mhogeweg** [comment]
I suspect this is because the user has a new DN and the old DN is stored in the geoportal database. The new active directory qualified name is likely different and that confuses the geoportal. You should be able to update the database and set the DN for this user to the new value. The user should then be able to login normally.

Marten

**Comment by StefanJaq** [comment]
Thanks for the hint, we will try

**Comment by gcampanile** [comment]
This happens also if you change the authentication method from simple to LDAP and try to use the same account name. The reason is the same: the users's DN is registered in the Geoportal's DB and an error is raised.
