### ISSUE TITLE
302-Found error appears when creating resource for ArcGIS Online feature service

### ISSUE THREAD

**Issue by jtrieber** [Esri/geoportal-server#197]
The "HTTP status code {302 - Found} received from server" error appears when trying to create a resource that would harvest metadata and capture information from an ArcGIS Online REST URL. Testing the connection displays as successful but fails when you try and create it.

Is it not possible to create a resource using ArcGIS Online feature services?

**Comment by mariczone** [comment]
I test register resource in http://gptogc.esri.com/geoportal/catalog/main/home.page with http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/SanFrancisco/311Incidents/FeatureServer and it work normally.

**Comment by mhogeweg** [comment]
That is because that is an ArcGIS server based service. We currently don't support registering ArcGIS online hosted services yet. These are not based on ArcGIS server and don't have the SOAP endpoint we have traditionally relied on.

You could use the editor and create a metadata record for the hosted services or use ArcGIS online to edit their metadata (this has been included since summer 2015). 

We can look at including this, but I would like to understand the use case

**Comment by jtrieber** [comment]
Hello Martin,

Thanks for the information about this. It is a solid answer that will help us move forward with our project.

Regards,
Jason Trieber
Summer Student – GIS Support Specialist
Alberta Energy Regulator
e Jason.Trieber@aer.ca<mailto:Jason.Trieber@aer.ca>  tel 403-297-6898  fax 403-297-7303
Suite 1000, 250 – 5 Street SW, Calgary, Alberta T2P 0R4
inquiries 1-855-297-8311 24-hour emergency 1-800-222-6514 www.aer.ca<http://www.aer.ca/>
