### ISSUE TITLE
How synchronization Metadata work?

### ISSUE THREAD

**Issue by mariczone** [Esri/geoportal-server#210]
I have some question about using synchronization function. Please guide me.

![2016-05-28_13-16-47](https://cloud.githubusercontent.com/assets/10164210/15625585/9a628df6-24d6-11e6-96eb-e5c5125535b0.png)
I would like to know about  how these below option work and setting.
1) Once every month 
2) Twice every month
3) Once every week
4) Once a day
5) Once an hour
6) Once only

Such as I choose Once every month then, **which day of month** will sync metadata of that record. 
Where I can setting about these option?

In gpt , I found only this configuration that may refer to these function , but don't have anything refer about date or something that will help me figure out about working for above option.

![3](https://cloud.githubusercontent.com/assets/10164210/15625622/0632a93e-24d8-11e6-9402-dcb66baddcda.png)

And I would like to know about what should I input in **pattern** textbox?
Can u give me an example of that input.

![2](https://cloud.githubusercontent.com/assets/10164210/15625605/732b8caa-24d7-11e6-8b7c-241b44458c7a.png)

Thank you for your helping.

**Comment by pandzel** [comment]
Choosing 'Periodically' allows to declare harvest frequency rather than specific date. For example, if 'Once every month' is selected it denotes monthly period. More precisely, it means that the next harvesting event for the repository will happen no sooner than one month since last harvest. This is regarding how that last harvest was triggered: by the user (by clicking one of the "Synchronization" buttons) or automatically as declared. If there was never harvesting performed before, that causes repository eligible for harvesting now.

Choosing 'At the specified time' it breaks relation with the last harvesting event and associates scheduling with the calendar.

With 'pattern' you have the ability to specify which exactly day of the week of the month it is. This is always a number. Examples will explain it better than words:
1. If you leave 'pattern' text box empty and select Monday, it means: every Monday,
2. If you enter, let's say: 2, it means every second Monday of the month.

Note! I've just tested this functionality it looks like there is a defect (you should only be able to pick either "Exact day" or "Pattern", not both). This was due to changes in Dojo version - got it fixed in current 'develop' branch; to be released soon.

**Comment by mariczone** [comment]
@pandzel Thank you for your help.
