### ISSUE TITLE
No LDAPS Support when connected to a secured LDAP

### ISSUE THREAD

**Issue by rwmajor2** [Esri/geoportal-server#60]
I am trying to configure Geoportal Server for Single Signon on a disconnected network using PKI/LDAP.  At the Tomcat level, I have everything working perfectly and I can see my cached credentials getting through to Geoportal Server.  However, the problem that is occurring according to the logs is Geoportal Server cannot establish a connection with our LDAP server, which is LDAPS secured.  For example, ldaps://myldap.server:636.

Does Geoportal Server support LDAPS?  If not, can we get this addressed quickly or someone tell me how to make it work?  It appears there are some settings in the gpt.xml (like securityProtocol) that may support this but I can't find any documentation on valid values.

The gpt.log file reports the following (much abbreviated since I am retyping this by hand):

SEVERE:  An error occurred while evaluating single sign-on credentials for:  MAJORRO
com.esri.gpt.framework.security.identity.IdentityException:  Unable to connect to LDAP.
      at com.esri.gpt............
      .............
Caused by:  javas.naming.CommunicationException:  simple bind failed:  myldapserver:636  [Root exception is javax.net.ssl.SSLHandshakeException:  sun.security.validator.ValidatorException:  PKIX path building failed:  unable to find valid certification path to requested target
      ..............

Thanks.

**Comment by gavincollins** [comment]
@rwmajor2 

"Caused by: javas.naming.CommunicationException: simple bind failed: myldapserver:636 [Root exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: unable to find valid certification path to requested target"

To connect via LDAPS you need to import into your keystore file the Root, Intermediate and Enterprise SSL certs of your Active Directory domain controller.
